# Generated by Django 2.1.7 on 2019-05-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book_id',
        ),
    ]
