# Generated by Django 2.1.7 on 2019-05-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_remove_comment_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='book_id',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='book_id',
            field=models.IntegerField(),
        ),
    ]
