# Generated by Django 2.2.1 on 2019-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20190511_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='link',
            new_name='uri',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='average_rating',
            field=models.IntegerField(default=-1),
        ),
    ]
