# Generated by Django 2.2.1 on 2019-05-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20190512_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='average_rating',
            new_name='votes',
        ),
    ]
