# Generated by Django 2.2.1 on 2019-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_auto_20190512_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
