# Generated by Django 2.1.7 on 2019-05-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_auto_20190512_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='vote',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
