# Generated by Django 2.2.1 on 2019-05-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_rating_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
    ]
